# Generated by Django 5.0.6 on 2024-07-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_date_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
