# Generated by Django 5.0.6 on 2024-07-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_born_alter_user_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_born',
        ),
    ]
