# Generated by Django 5.0.6 on 2024-06-11 16:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 11, 10, 4, 28, 922308)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
