# Generated by Django 5.0.6 on 2024-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='users_assigned',
            field=models.ManyToManyField(related_name='class_users', to='users.user'),
        ),
    ]
