# Generated by Django 5.0.6 on 2024-07-17 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='users_assigned',
            field=models.ManyToManyField(blank=True, related_name='class_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
