# Generated by Django 5.0.6 on 2024-06-11 01:56

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='users_assigned',
            field=models.ManyToManyField(blank=True, related_name='class_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
