# Generated by Django 5.0.6 on 2024-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='membership_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
