# Generated by Django 5.0.6 on 2024-07-30 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_payment_membership_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='SINPE', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership_expiration',
            field=models.DateField(default=datetime.datetime(2024, 8, 28, 18, 54, 31, 147626)),
        ),
    ]
